root: true

parserOptions:
  ecmaVersion: latest
  sourceType: 'module'

env:
  es2022: true
  browser: true

extends: htmlacademy/vanilla

rules:
  indent:
    - error
    - tab
    - SwitchCase: 1

overrides:
  - files:
      - '*.ts'
    extends:
      - plugin:@typescript-eslint/recommended
    parser: "@typescript-eslint/parser"
    parserOptions:
      ecmaVersion: latest
    plugins:
      - "@typescript-eslint"
    rules:
      no-shadow: off
      '@typescript-eslint/no-shadow': error
      '@typescript-eslint/no-non-null-assertion': off
      '@typescript-eslint/no-duplicate-enum-values': off
      no-use-before-define: off
      "@typescript-eslint/no-use-before-define": error
